run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - misspell
    - bodyclose
    - ineffassign
    - revive
  disable:
    - unused  # staged code for future features

linters-settings:
  revive:
    severity: warning
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true

issues:
  exclude-use-default: false
